### ISSUE TITLE
setValidation issue

### ISSUE THREAD

**Issue by oriceon** [bllim/laravalid#1]
Hello, i tested this package and i see that setValidation from a controler don`t to that is supposed to 

``` php
\Form::setValidation($rules);
```

Directly from view, jquery validation is workin well

``` php
Form::open(array('url' => 'foo/bar', 'method' => 'put'), $rules);
```

**Comment by bgultekin** [comment]
Hi, I tried but couldn't regenerate the bug you have mentioned. Can you provide more detail?

**Comment by oriceon** [comment]
I set it în controller but doesn't append any rules to form inputs.
Pe 24 mar. 2015 11:03, "Bilal Gültekin" <notifications@github.com> a scris:

**Comment by oriceon** [comment]
I set it în controller but doesn't append any rules to form inputs.

Controller:

``` php
    public function getRegister()
    {
        $rules = ['given_name' => 'required'];
        \Form::setValidation($rules);

        return view('auth.register');
    }
```

View

``` php
{!! Form::open(['url' => route('post.register'), 'id' => 'register-form', 'class' => 'live-validate']) !!}

<li{!! ($errors->has('given_name')) ? ' class="has-error"' : '' !!}>
    {!! Form::label('given_name', trans('register.given_name')) !!}
    {!! Form::text('given_name', null, ['id' => 'given_name', 'placeholder' => trans('register.given_name_placeholder')]) !!}
    {!! Form::label('given_name', $errors->first('given_name'), ['class' => 'small error' . ( ! $errors->has('given_name') ? ' hidden' : '')]) !!}
</li>

<li>
{!! Form::submit(trans('register.submit_button'), ['class' => 'button big green']) !!}
</li>

{!! Form::close() !!}
```

footer.blade.php

``` javascript
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
<script src="{{ asset('laravalid/jquery.validate.laravalid.js') }}"></script>
<script type="text/javascript">
  $(document).ready(function() {
      $('.live-validate').validate({
          onkeyup: false
      });
  });
</script>
```

**Comment by oriceon** [comment]
Did you regenerare the bug? :|

**Comment by bgultekin** [comment]
I couldn't regenerate. Are you sure there isn't any redirect? Are you sure there isn't any attribute related to validation of given_name input in html code (this may be related to js error)?

**Comment by oriceon** [comment]
On a fresh laravel 5 installation i confirm that it work.

In curent laravel i have an attribute named given_name in validator trans.

``` php
 'attributes' => [
        'given_name'       => 'prenume',
        ...
]
```

Could be from there?

Anyway, another thing, You forgot to call 'use Lang;' in

``` php
FatalErrorException in /var/www/laravel/vendor/bllim/laravalid/src/Bllim/Laravalid/Converter/Base/Converter.php line 218: Class 'Bllim\Laravalid\Converter\Base\Lang' not found
```

**Comment by bgultekin** [comment]
I am not sure. Can you disable it and try?

24 Mar 2015 Sal, 16:44 tarihinde, Valentin Ivaşcu notifications@github.com
şunu yazdı:

**Comment by oriceon** [comment]
I tryed in fresh installation and is not from lang attribute. :|
Have any ideea what else to debug?

**Comment by oriceon** [comment]
What i'm seeing is that `setValidation()` is workin from view.
The problem it is in controller but cound't find what could be.

**Comment by bgultekin** [comment]
The main reason may be reconstructing of FormBuilder class. You can check it with debug tools by putting an break point in FormBuilder (of laravalid) or simpler via var_dump.

**Comment by david-macias** [comment]
I'm having the exact same issue.

**Comment by oriceon** [comment]
Could you paste your composer.json please?

**Comment by david-macias** [comment]
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "laravel/framework": "5.0._",
        "illuminate/html": "~5.0",
        "appitventures/phpgmaps": "2.0._@dev",
        "bllim/laravalid": "*"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-create-project-cmd": [
            "php -r \"copy('.env.example', '.env');\"",
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

**Comment by oriceon** [comment]
@bllim I found the problem. Was because i had some hidden forms in view and using setvalidation from controller will call resetValidation() method from FormBuilder class and destroy $this->validationRules

Could you make a second param to Form::setValidation to give form id and catch all $this->validationRules for that one?

**Comment by bgultekin** [comment]
Okey @oriceon I'll give a look. That would be more useful.
