### ISSUE TITLE
Same özelliği çeviri hatası

### ISSUE THREAD

**Issue by ozgur-keles** [bllim/laravalid#13]
Selamlar,

master branch'indeki kodu kullanıyorum. Same özelliği ile alakalı bir sorunum daha var. :attribute yerine validation.php 'nin en altına yazdığım türkçe metinleri göstermiyor input name çıkıyor. İkincisi de :other yerine diğer input adının türkçeleştirilmiş hali yazması gerekiyordu fakat :other diye yazıyor.

Teşekkürler.

**Comment by bgultekin** [comment]
Merhaba,

Son bir iki commit oldu. Onlardan sonra deneme imkanın oldu mu? Ayrıca laravel 4 sürümü için mi yoksa 5 sürümü için mi problem var?

**Comment by igorsantos07** [comment]
What?! 
Please write and reply issues in English, so other developers can see what's going on!

**Comment by maydemirx** [comment]
@igorsantos07 @ozgur-keles 's problem like that:

I use master brach code. I have a problem for same rule. The :attribute can not be translated. İt always shows :attribute in error messages. And other problem is related to :other attribute. I even add translate for :other it always shows :other in error message.

**Comment by phpspider** [comment]
This may help :
https://github.com/bllim/laravalid/issues/26

**Comment by nthachus** [comment]
It was resolved, please update and check
