### ISSUE TITLE
"unique" validation works incorrectly

### ISSUE THREAD

**Issue by maydemirx** [bllim/laravalid#16]
Hi,

i am using laravalid validation unique rule for email verification. If i click to submit button at form ajax returned internal server error (500).  Error is: 

<code>SQLSTATE[42703]: Undefined column: 7 ERROR: column "input" does not exist LINE 1: select count(_) as aggregate from "users" where "input" = $1 ^ (SQL: select count(_) as aggregate from "users" where "input" = maydemirx@gmail.com)</code>

your code Converter/Base/Route.php is:

<code>
$validator = \Validator::make(
            array('input' => $parameters['value']),
            array('input' => $name.':'.Helper::decrypt($parameters['validationParameters']))
        );

```
    return ['valid' => !$validator->fails(), 'messages' => $validator->messages()];
```

</code>

validator send column name as "input". But column name must be "email".

**Comment by bgultekin** [comment]
Hi,

Laravel 4 or 5 ? Also, Did you try after new commits?

**Comment by maydemirx** [comment]
Laravel 5

**Comment by bgultekin** [comment]
I tried. It works. Can you give more information? Also did you try with latest version?
