### ISSUE TITLE
Rule "same" does not pull custom message from laravel.

### ISSUE THREAD

**Issue by sstepane** [bllim/laravalid#17]
Hi,

Thanks for the package in the first place!

I've been playing around with it and found that rule "same" does not pull custom message from laravel.
Found that it retrieves its message a different way among all other methods in Message.php.
Made quick fix for this:
public function same($parsedRule, $attribute, $type) 
    {
        //$message = Lang::get('validation.'.$parsedRule['name'], ['attribute' => $attribute]);
        $message = Helper::getValidationMessage($attribute, $parsedRule['name']);
        return ['data-msg-equalto' => $message];
    }

So it would work. I'm not sure if it is usefull to work out all of "same" rule tidbits (to mention the field it referres to) as in any case (to my best understanding) it will need its own custom message to display to be meaningfull to user.

**Comment by nthachus** [comment]
It should work correctly now, please check
