### ISSUE TITLE
When support for laravel 5.1 with collectives?

### ISSUE THREAD

**Issue by kaidoj** [bllim/laravalid#19]
Nvm. I did it myself.

**Comment by igorsantos07** [comment]
Would you explain what was your issue, and your solution? 
Are you talking about support to LaravelCollective's HTML?

**Comment by kaidoj** [comment]
I got error when trying to do phpunit testing. 
I changed in 
FormBuilder.php line 24 to

``` php
class FormBuilder extends \Collective\Html\FormBuilder {
```

and line 28 to

``` php
public function __construct(\Collective\Html\HtmlBuilder $html, \Illuminate\Routing\UrlGenerator $url, $csrfToken, Converter\Base\Converter $converter)
```

and in LaravalidServiceProvider.php line 51 to 

``` php
return new \Collective\Html\HtmlBuilder($app['url']);
```

After these changes everything working and no errors in laravel 5.1.

**Comment by kaidoj** [comment]
I added a pull request for 5.1 support.

**Comment by igorsantos07** [comment]
So, the support for LaravelCollective is just some lines of changes? Cool!
Hopes the PR gets accepted :)

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by kaidoj** [comment]
Atm im using it. No errors so far everything working.
