### ISSUE TITLE
Having trouble getting the form to validate

### ISSUE THREAD

**Issue by jshah4517** [bllim/laravalid#2]
Hi there, thanks for this package. I'm trying to implement it in my project however I can't seem to get the form to actually validate on submit.

I've followed the usage guide and noticed that the form HTML elements do have extra attributes for the validation which seems correct, but the form strangely has novalidate="novalidate" - not sure this is correct.

Do you have any idea what might be wrong?

**Comment by bgultekin** [comment]
Hi, as i remember, package doesn't add any attribute to form tag, just to form elements. If you can share your code, i can help more.

**Comment by jshah4517** [comment]
In the controller I have:

```
public $rules = [
    'name'   => 'required|min:1',
    'colour' => [ 'regex:/#([a-f]|[A-F]|[0-9]){3}(([a-f]|[A-F]|[0-9]){3})?\b/' ]
];
```

```
Form::setValidation($this->rules);
return View::make('user::operator.forms.group')
       ->with('record', new UserGroup());
```

In the view, I simply have:

```
{!! Form::open([ 'route' => 'user.operator.group.store' ]) !!}

...

<script src="{{ asset('resources/assets/libs/jquery-validation/js/jquery.validate.min.js') }}"></script>
<script src="{{ asset('resources/assets/libs/laravalid/jquery.validate.laravalid.js') }}"></script>
<script type="text/javascript">
    $('form').validate({onkeyup: false});
</script>
```

This is what is generated:

```
<form method="POST" action="http://localhost/project/admin/user/group" accept-charset="UTF-8" novalidate="novalidate">

        <div class="form-row">
            <label for="name">Name</label>
            <div class="input-container">
                <input data-rule-required="true" data-msg-required="The name field is required." data-rule-minlength="1" data-msg-minlength="The name must be at least 1 characters." name="name" type="text" id="name" data-cip-id="name">
            </div>
        </div>
```

Nothing happens on clicking submit.

**Comment by bgultekin** [comment]
I couldn't see any problem with Laravalid. Probably, as you said, jquery validate library doesn't validate because of novalidate attribute. Sorry for late reply. 
Lastly, if you find anything wrong with laravalid during debug, please send pull request or share the bug.

**Comment by jshah4517** [comment]
Laravalid appears to be adding the novalidate attribute automatically from what I understand. I will have a closer look another day, but it'd be interesting to see if anyone else has a similar issue.

**Comment by bgultekin** [comment]
Ok, issue might stay open for a while.

**Comment by nthachus** [comment]
jQuery.validate library will auto-add attribute novalidate="novalidate" to `form` tag, so, there is no wrongs here :-)
