### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by phpspider** [bllim/laravalid#26]
It's support multilanguage that i know. I want to know how do i display the attribute name in the selected language. We are defining key names in the controller and field/column in validation message displayed on that basis.
e.g.
$rules = ['User Name' => 'required|min:3|max:60', 'User Password' => 'required|min:7|max:25'];
if we use the above rule in controller it will look for User Name and show the message as per the validation file defined in lang folder.
Defined in lang file : "The :attribute field is required."
It will show ""The User Name field is required."

But in case of another language like in hindi how do we show User Name in hindi.

**Comment by bgultekin** [comment]
Try attributes key in lang/{{ your lang}}/validation.php :

``` php
    /*
    |--------------------------------------------------------------------------
    | Custom Validation Attributes
    |--------------------------------------------------------------------------
    |
    | The following language lines are used to swap attribute place-holders
    | with something more reader friendly such as E-Mail Address instead
    | of "email". This simply helps us make messages a little cleaner.
    |
    */

    'attributes' => ['User Name' => 'User Name in Your Lang'],
```

**Comment by phpspider** [comment]
Thanks its working.
