### ISSUE TITLE
Installation instructions incorrect?

### ISSUE THREAD

**Issue by david-macias** [bllim/laravalid#3]
Is this correct in your install instructions?

``` php
    'providers' => array(
        ...
            'HTML'      => 'Illuminate\Support\Facades\HTML', // if not exists add for html too
            'Form'      => 'Bllim\Laravalid\Facade',
    ),

Should it be aliases and what if you already have a Form alias?
```

**Comment by bgultekin** [comment]
Yes you are right :) sorry for mistake.

**Comment by david-macias** [comment]
Yeah that looks better. The other thing was a question about what if you already have a form alias, will adding your alias cause an issue?

**Comment by bgultekin** [comment]
You should update current Form alias with "Bllim\Laravalid\Facade". You can continue to use it like old one. It is already extending Illuminate's Form (\Illuminate\Html\FormBuilder).
