### ISSUE TITLE
unresolvable dependencies for people on 5.2

### ISSUE THREAD

**Issue by lostdreamer** [bllim/laravalid#30]
the newest version (1.1.1) is 5.2 ready but the composer.json still requires "laravelcollective/html": "5.1.*"

This creates unresolvable dependencies resulting in not installing the newest version of laravalid, which in turn results in a not working version.

**Comment by bgultekin** [comment]
can you check with master branch if this fixed it?

**Comment by bgultekin** [comment]
Can you try master branch? I committed new composer.json file but i did not
release version because i couldn't try yet.

26 Ara 2015 Cmt 06:09 tarihinde lostdreamer notifications@github.com şunu
yazdı:
