### ISSUE TITLE
Multiple inputs with same name using array.

### ISSUE THREAD

**Issue by phpspider** [bllim/laravalid#31]
I am creating a form which is containing inputs and they are repeating again and again. There name and id is generating programmatically.

e.g. my input is :

{!! Form::select("demo[' + (Demo.id) + '][location]",array("" => "Select Loc",1=>"Loc1",2=>"Loc2") , "",array("id"=>"demo_"'+ Demo.id +'","class"=>"form-control") !!}

Suppose Demo.id is getting dynamically when someone clicks on add more button it will create this element with new Demo.id

So how we can implement validations on these type of fields.

**Comment by kaidoj** [comment]
Atm i think u cannot validate like this with laravalid. After laravalid has done validation it will still validate after submit if u use laravel validation rules.

``` php
$data = $request->all();
$rules = [];
if(isset($data['demo']) && is_array($data['demo'])) {
    foreach($data['demo'] as $key => $val) {
        $rules['demo.' . $key . '.location'] = 'max:255'; 
    }
}
$validator = Validator::make($data, $rules);
//etc...
```

Feel free to make PR to make it work with laravalid.

**Comment by phpspider** [comment]
@kaidoj  Thanks for update. But how client side validations occur ?

**Comment by kaidoj** [comment]
@phpspider It does not occur if u do not do it yourself on the client side. Like i said feel free to make a PR so it will work in laravalid.
