### ISSUE TITLE
Validation not fired on second form

### ISSUE THREAD

**Issue by arieswandari** [bllim/laravalid#33]
The designer has two form in one page, and the validation only fired in the first form. Validation not fired in the second form. I'm already differentiate form name as below. 

{!! Form::open(['route' => 'sessions.store', 'method' => 'post', 'name' => 'loginForm'], $loginRules) !!}
{!! Form::open(['route' => 'users.store', 'method' => 'post', 'name' => 'registerForm'], $regRules) !!}

If I delete the first form, then validation in second form will fired.

**Comment by phpspider** [comment]
Did you pass the form name from controller as well ?

**Comment by kaidoj** [comment]
If u have multiple forms same page it works like this.

``` php
//in controller u need to give both forms unique name
Form::setValidation($loginRules, 'loginForm');
Form::setValidation($regRules, 'registerForm');
return view('your-view-path');

//then in view
{!! Form::open(['route' => 'sessions.store', 'method' => 'post', 'name' => 'loginForm']) !!}
{!! Form::close() !!}}
{!! Form::open(['route' => 'users.store', 'method' => 'post', 'name' => 'registerForm']) !!}
{!! Form::close() !!}}
```

``` javascript
//ofc u need to use
$('form[name=loginForm]').validate({onkeyup: false});
$('form[name=registerForm]').validate({onkeyup: false});
```

This works i tested it.

**Comment by arieswandari** [comment]
Thank you kaidoj, this solve the problem.
