### ISSUE TITLE
Error while upgrading to laravel 5.2

### ISSUE THREAD

**Issue by filpgame** [bllim/laravalid#34]
When i was upgrading my project to laravel 5.2, i get this error:

```
Argument 3 passed to Collective\Html\FormBuilder::__construct() must implement interface Illuminate\Contracts\View\Factory, string given, 
called in vendor/bllim/laravalid/src/Bllim/Laravalid/FormBuilder.php on line 30 and defined (View: resources/views/auth/login.blade.php).
```

According to [this commit](https://github.com/LaravelCollective/html/commit/4c9b44a817543bd0ef7f0ca8c8a63e5556504274) there's a new parameter that should be passed to Collective\Html\FormBuilder constructor. The `Factory $view` parameter. 

How to solve this?
EDIT: I sent a PR to fix this

**Comment by r-springmann** [comment]
@filpgame i made a fork (https://github.com/r-springmann/laravalid) of your fork to correct the naming of the package so that composer could find the fork

**Comment by george1974** [comment]
I am getting the same error when using this package with Laravel 5.2.x. Please let me know when are you planning to release the fix for this issue.

**Comment by manojsharma20** [comment]
I am also getting the same issue when i install into fresh laravel 5.2. Please check what is the issue and let us know.

**Comment by nthachus** [comment]
It was resolved now, please check
