### ISSUE TITLE
Group validations

### ISSUE THREAD

**Issue by phpspider** [bllim/laravalid#36]
This is not an issue. Just a question. Is there any way that we can apply validations on a groups on input elements.

e.g. if i have multiple payment blocks 1,2,3,etc. and each block is having 3 or 4 input elements. So if i enter in input1 of block1 then validations over other input boxes of block1 should applied not on payment blocks 2,3,etc without filling them.

**Comment by kaidoj** [comment]
Why not make each payment into its own form? Then u can validate them separately.

``` html
<form id="payment1">
     <input type="text" name="payment1text">
</form>
<form id="payment2">
     <input type="text" name="payment2text">
</form>
```
