### ISSUE TITLE
getValidationRule() crashes when asking for a field that has no rules

### ISSUE THREAD

**Issue by igorsantos07** [bllim/laravalid#37]
I've fixed this in a fork, you can cherry-pick it: https://github.com/laravel-ardent/laravalid/commit/43bc5398f2f7a9306f0eab9ed4a8414edd838c3c. I was unable to easily separate it in a branch for a PR.

**Comment by nthachus** [comment]
Method `Converter::checkValidationRule` already do that check :-)
