### ISSUE TITLE
Problem on case sensitive systems

### ISSUE THREAD

**Issue by chosten** [bllim/laravalid#4]
Hello,

Could you rename the folder "converter" inside "laravalid/src/Bllim/Laravalid/" into "Converter". (Notice the capital "C")
Otherwise I'm getting a runtime exception with composer:

```
PHP Fatal error:  Class 'Bllim\Laravalid\Converter\JqueryValidation\Converter' not found in /vendor/bllim/laravalid/src/Bllim/Laravalid/LaravalidServiceProvider.php on line 58
```

Thank you.

**Comment by bgultekin** [comment]
Hi, i commited some changes, is it okey now? I couldn't check because i am on case insensitive system.

**Comment by chosten** [comment]
Yes, it's ok now, thank you.

**Comment by chosten** [comment]
I've just tried to update to the latest release and it's broken.
I'm not sure what happened but there are a few files missing inside the new Converter folder. (Converter.php, Message.php and Rule.php)

**Comment by bgultekin** [comment]
I published new release for this error. You can fix it by update.
