### ISSUE TITLE
Error while using FormBuilder, String given.

### ISSUE THREAD

**Issue by manojsharma20** [bllim/laravalid#41]
I am getting bellow error when try to resolved [https://github.com/bllim/laravalid/issues/34](https://github.com/bllim/laravalid/issues/34)

I have changed :

From

`$form = new FormBuilder($app->make('html'), $app->make('url'), $app->make('session.store')->getToken(), $converter);`

To
`
$form = new FormBuilder($app['html'], $app['url'], $app['view'], $app['session.store']->getToken(), $converter);`

Argument 4 passed to Bllim\Laravalid\FormBuilder::__construct() must be an instance of Bllim\Laravalid\Converter\Base\Converter, string given

How to resolved these issue. 

Is this Form support model populating like Collective Form support ?

**Comment by nthachus** [comment]
It was resolved, and, yes, because this Form is inherited from Collective Form :-)
