### ISSUE TITLE
FatalErrorException

### ISSUE THREAD

**Issue by oriceon** [bllim/laravalid#5]
FatalErrorException in LaravalidServiceProvider.php line 58: Class 'Bllim\Laravalid\Converter\JqueryValidation\Converter' not found

```
in /var/www/vendor/bllim/laravalid/src/Bllim/Laravalid/LaravalidServiceProvider.php line 58
```

**Comment by bgultekin** [comment]
I published v1.0.6 release for this, you can update. Sorry for this error, I tried to fix a case sensitive error, from a case insensitive os. This issue is the result of try :) .

**Comment by oriceon** [comment]
Thanks for quick fix. I still have #1 issue but tomorrow maybe i`ll have some time to dig in.

**Comment by bgultekin** [comment]
Unfortunately, I couldn't regenerate it although I tried on fresh laravel-5 installation. If you can find something about it, please send pull-request or comment in #1 so i can fix. Thanks.
