### ISSUE TITLE
Issues with laravel4 branch and config

### ISSUE THREAD

**Issue by felorhik** [bllim/laravalid#6]
First in the LaravelidServiceProvider the `$userConfigFile` is wrong.
It needs to be `$userConfigFile    = app_path('config/packages/laravalid/config.php');` (was missing packages).

I noticed this when trying to create my own config to disable laravel based messages. Changing the useLaravelMessages to false also caused an error at line 156 of `Base\Converter`. This was fixed by moving `$outputAttributes = $outputAttributes + $messageAttributes;` a few lines above and inside the if statement for checking the config result.

Also as a note the documentation does not reflect laravel 4 for generating assets/configs, still new to laravel but could not use the example command (`php artisan vendor:publish`), nor the normal command for laravel to generate a config (`php artisan config:publish`), had to create the file manually (although `php artisan asset:publish` worked).

Great work on this overall though, its nice to have to only manage rules in one place.

**Comment by yapsr** [comment]
@bllim could you please merge this into the dev-laravel4 branche?

And in stead of 
$userConfigFile    = app_path('config/packages/laravalid/config.php');
I would use 
$userConfigFile    = app_path('\config\packages\bllim\laravalid\config.php');

**Comment by nthachus** [comment]
This should work well now, please check :-)
