### ISSUE TITLE
Form name parameter for Form::setValidation method

### ISSUE THREAD

**Issue by bgultekin** [bllim/laravalid#7]
Form::setValidation method is working like `Form::setValidation($rules);` , it will also work like `Form::setValidation($name, $rules);`

**Comment by oriceon** [comment]
Thanks. Any ideea when relase this?

**Comment by oriceon** [comment]
Hi! Any news about that?

**Comment by bgultekin** [comment]
Unfortunately no, I even find time hardly to reply messages :\ . But if you can send pull request I try to look and accept quickly. Thank you for your understanding.
