### ISSUE TITLE
Error in Laravel 5

### ISSUE THREAD

**Issue by ghost** [bllim/laravalid#8]
Hi,

u will use HTML/Illuminate. This is outdated.

So I get the error, that Laravel will have a collective instance and get an Illuminate Instance.

Can u correct this?

http://laravelcollective.com

**Comment by bgultekin** [comment]
Yes it is, but you can still use it. When you install this package, composer installs also Illuminate/HTML automatically. Follow the installation instructions. If you still have error, please provide more detail.

**Comment by ghost** [comment]
Hi,

I've got an error, because you will use the same facade like Laravel Collective.

U use:

> Bllim\Laravalid\Facade

And Laravel Collection use

> Collective\Html\FormFacade

Please fix your facade!

**Comment by ghost** [comment]
Forget:

Both aliases are 

> Form
> 
> 'Form'      => 'Bllim\Laravalid\Facade',
> 'Form' => 'Collective\Html\FormFacade',
